import { PublicHeader } from "@/components/layout/public-header";
import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--background)]">
      <PublicHeader />
      <div className="pt-24 pb-16 px-4">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
          <p className="text-sm text-[var(--muted-foreground)] mb-8">
            Last updated: March 30, 2026
          </p>

          <div className="space-y-6 text-sm text-[var(--muted-foreground)] leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-[var(--foreground)] mb-2">1. Service Description</h2>
              <p>Geothority (&quot;the Service&quot;) is a SaaS platform that provides website scanning, local SEO analysis, content generation, and CMS publishing tools designed for independent insurance agents.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[var(--foreground)] mb-2">2. Account Terms</h2>
              <ul className="list-disc pl-5 space-y-1">
                <li>You must be 18 years or older to use this Service.</li>
                <li>You must provide accurate business information for scans to work correctly.</li>
                <li>You are responsible for maintaining the security of your account.</li>
                <li>One person or legal entity per account.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[var(--foreground)] mb-2">3. Subscription & Payment</h2>
              <ul className="list-disc pl-5 space-y-1">
                <li>Subscriptions are billed monthly via Stripe.</li>
                <li>All plans include a free website scan before subscribing.</li>
                <li>You may cancel your subscription at any time; access continues until the end of the billing period.</li>
                <li>Refunds are available within 14 days of initial purchase if no content has been published.</li>
                <li>Prices may change with 30 days notice via email.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[var(--foreground)] mb-2">4. Content Ownership</h2>
              <p>Content generated through Geothority belongs to you. You have full rights to use, modify, and publish generated content on your website. We retain no ownership rights over your generated content.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[var(--foreground)] mb-2">5. CMS Publishing</h2>
              <ul className="list-disc pl-5 space-y-1">
                <li>When you connect a CMS, you authorize Geothority to create and publish pages on your behalf.</li>
                <li>You can revoke CMS access at any time through Settings.</li>
                <li>We are not responsible for any changes made by third parties to published content.</li>
                <li>Publishing credentials are encrypted and never shared.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[var(--foreground)] mb-2">6. AI-Generated Content Disclaimer</h2>
              <p>Content generated by our AI tools is meant to serve as a high-quality starting point. While we strive for accuracy, you should review all generated content before publishing. Geothority does not guarantee specific search ranking results.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[var(--foreground)] mb-2">7. Acceptable Use</h2>
              <p>You agree not to:</p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>Use the Service for any illegal purpose</li>
                <li>Generate content for businesses you do not own or represent</li>
                <li>Attempt to reverse-engineer our scanning algorithms</li>
                <li>Resell or redistribute generated content as a service</li>
                <li>Abuse the API or scanning functionality</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[var(--foreground)] mb-2">8. Service Availability</h2>
              <p>We strive for 99.9% uptime but do not guarantee uninterrupted service. Scheduled maintenance will be communicated in advance when possible.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[var(--foreground)] mb-2">9. Limitation of Liability</h2>
              <p>Geothority is provided &quot;as is.&quot; We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service, including but not limited to changes in search rankings or business performance.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[var(--foreground)] mb-2">10. Termination</h2>
              <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time; all data will be removed within 30 days.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[var(--foreground)] mb-2">11. Contact</h2>
              <p>Questions about these terms? Contact us at: <a href="mailto:hello@geothority.io" className="text-emerald-500 hover:underline">hello@geothority.io</a></p>
            </section>
          </div>
        </div>
      </div>

      <footer className="border-t border-[var(--border)] py-8 px-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between text-sm text-[var(--muted-foreground)]">
          <Link href="/" className="hover:text-[var(--foreground)]">← Back to home</Link>
          <Link href="/privacy" className="hover:text-[var(--foreground)]">Privacy Policy →</Link>
        </div>
      </footer>
    </div>
  );
}
