// ============================================================
// Content Generation Module – Types & Interfaces
// ============================================================

/** Supported content types for generation */
export type ContentType = "landing_page" | "blog_post" | "service_page" | "localized_faq" | "trust_page" | "about";

/** SEO optimization targets */
export interface SEOTargets {
  primaryKeyword: string;
  secondaryKeywords: string[];
  city: string;
  state?: string;
  targetWordCount: { min: number; max: number };
  cityMentionRange: { min: number; max: number };
}

/** Local relevance configuration */
export interface LocalRelevanceConfig {
  city: string;
  state?: string;
  landmarks?: string[];
  neighborhoods?: string[];
  nearbyCities?: string[];
  localEvents?: string[];
  localStatistics?: string;
}

/** AI Summarization optimization flags */
export interface AISummarizationConfig {
  /** Include a concise TL;DR summary paragraph at the top */
  includeSummary: boolean;
  /** Use structured data (FAQ schema, HowTo schema) for AI parsing */
  includeStructuredData: boolean;
  /** Add clear heading hierarchy for AI extractors */
  strictHeadingHierarchy: boolean;
  /** Include "People Also Ask" style questions */
  includePAAQuestions: boolean;
}

/** A content brief generated by AI before drafting */
export interface ContentBrief {
  id: string;
  contentType: ContentType;
  title: string;
  metaTitle: string;
  metaDescription: string;
  outline: ContentSection[];
  seoTargets: SEOTargets;
  localRelevance: LocalRelevanceConfig;
  aiConfig: AISummarizationConfig;
  targetAudience: string;
  toneAndStyle: string;
  competitorInsights?: string;
  suggestedInternalLinks?: string[];
  createdAt: string;
}

/** A section within a content brief outline */
export interface ContentSection {
  heading: string;
  headingLevel: 2 | 3 | 4;
  keyPoints: string[];
  targetWordCount: number;
  localRelevanceHint?: string;
}

/** Generated content output */
export interface GeneratedContentOutput {
  title: string;
  metaTitle: string;
  metaDescription: string;
  contentHtml: string;
  contentMarkdown: string;
  schema: Record<string, unknown>;
  summary: string; // TL;DR for AI summarization
  qualityScore: number;
  seoChecklist: SEOChecklistResult;
}

/** SEO checklist validation result */
export interface SEOChecklistResult {
  titleUnder60Chars: boolean;
  metaUnder160Chars: boolean;
  hasH1: boolean;
  headingHierarchy: boolean;
  cityMentions: number;
  keywordInTitle: boolean;
  keywordInFirstParagraph: boolean;
  hasInternalLinks: boolean;
  hasSchema: boolean;
  wordCount: number;
  overallScore: number;
}

/** Content generation request */
export interface ContentGenerationRequest {
  contentType: ContentType;
  businessName: string;
  agentName?: string;
  city: string;
  state?: string;
  service?: string;
  targetKeyword?: string;
  scanId?: string;
  /** If provided, skip brief generation and use this brief */
  brief?: ContentBrief;
  /** Industry vertical (defaults to insurance) */
  industry?: string;
  /** Additional context from competitor analysis */
  competitorContext?: string;
}

/** Content brief generation request */
export interface BriefGenerationRequest {
  contentType: ContentType;
  businessName: string;
  city: string;
  state?: string;
  service?: string;
  targetKeyword?: string;
  industry?: string;
  competitorContext?: string;
}
